import React from "react";
import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import {
  SiJavascript,
  SiMongodb,
  SiPhp,
  SiReact,
  SiTypescript,
  SiSass,
  SiNodedotjs,
  SiRedux,
} from "react-icons/si";
import { useState, useEffect } from "react";
import AOS from "aos";
import "aos/dist/aos.css";

export default function Home() {
  const [darkMode, setDarkmode] = useState(false);
  useEffect(() => {
    AOS.init();
  }, []);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>BeardKoda </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 md:px-20 lg:px-60  dark:bg-gray-800">
        <section className="  min-h-screen">
          <nav
            className=" py-10 mb-12 flex justify-between"
            data-aos="zoom-in-right"
            data-aos-duration="1500"
          >
            <h1 className=" text-xl font-semibold font-burtons dark:text-white">
              BeardKoda
            </h1>
            <ul className=" flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkmode(!darkMode)}
                  className=" text-2xl cursor-pointer  dark:text-white"
                />
              </li>
              <li>
                <a
                  href="#"
                  className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-7"
                >
                  Contact Me
                </a>
              </li>
            </ul>
          </nav>
          <div className=" text-center p-10 dark:text-white">
            <p>Hi!, It's </p>
            <h2
              className=" text-2xl text-teal-500 font-semibold pb-2 md:text-3xl lg:text-5xl"
              data-aos="fade-right"
              data-aos-duration="1500"
            >
              BeardKoda{" "}
              <span className=" text-sm text-black dark:text-white">
                here 🤞,
              </span>
            </h2>
            <h3 className=" text-xl py-2 font-medium md:text-2xl lg:text-5xl ">
              I'm a Software Engineer,
            </h3>
            <p className=" text-md py-5 leading-7 text-gray-800 md:text-xl max-w-xl mx-auto lg:text-xl max-w-xl mx-auto dark:text-white">
              Automation is everything to me, I love learning new things
              everyday from programming languages, programming tools, automation
              tools and Games.
            </p>
          </div>

          <div
            className=" text-5xl flex justify-center gap-5 py-3 text-gray-500 dark:text-teal-500"
            data-aos="fade-right"
            data-aso-duration=" 1000"
          >
            <a href="https://www.linkedin.com/in/joshua-akinsuyi/">
              <AiFillLinkedin />
            </a>
            <a href="https://twitter.com/BeardKoda">
              {" "}
              <AiFillTwitterCircle />
            </a>
            <a href="https://github.com/BeardKoda">
              {" "}
              <AiFillGithub />
            </a>
          </div>
        </section>

        <section>
          <div className=" mt-2 min-h-screen">
            <div className="text-center my-10  ">
              <h3
                className=" text-3xl py-1 text-teal-500 justify-center flex"
                data-aos="fade-up"
                data-aos-duration="2000"
              >
                Services I offer
              </h3>
              <p
                className=" text-md  py-5 leading-8 text-gray-800 text-center md:text-xl max-w-xl mx-auto lg:text-xl max-w-xl mx-auto dark:text-white"
                data-aos="fade-up"
                data-aos-duration="3000"
              >
                {" "}
                "since the beginning of my journey as a Developer, I've done
                remote work for <span className=" text-teal-500">agencies</span>
                , consulted for <span className=" text-teal-500">startups</span>{" "}
                and collaborated with talented people to create didgital product
                for bith business and consumer use."
              </p>
              <p
                className=" text-md py-5 leading-7 text-center text-gray-800 md:text-xl max-w-xl mx-auto lg:text-xl max-w-xl mx-auto dark:text-white"
                data-aos="fade-up"
                data-aos-duration="9000"
              >
                I offer from a wide range of Services, including Database
                Analyst, FullStack Devloper And DataScientist.
              </p>
            </div>

            <div data-aos="zoom-in" data-aos-duration="1000">
              <div className=" text-center  mt-10 py-14 ">
                <h4 className=" text-3xl py-1 text-teal-500 text-center mb-3">
                  Skills
                </h4>
                <p className=" text-center md:text-xl max-w-2xl mx-auto lg:text-xl max-w-xl mx-auto dark:text-white">
                  4 years+, a ton of tutorials and online courses, here I am. A
                  passion of mine is translating logic and designs into code.
                  Here are some the tools I use
                </p>
              </div>
            </div>

            <div
              className="flex justify-between  m-4 text-teal-800 my-5 w-50 md:ma-w-xl lg: max-w-xl mx-auto   dark:text-teal-500"
              data-aos="fade-up-left"
            >
              <SiJavascript className=" text-2xl" />
              <SiMongodb className=" text-2xl" />
              <SiPhp className=" text-2xl" />
              <SiReact className=" text-2xl" />
              <SiTypescript className=" text-2xl" />
              <SiNodedotjs className=" text-2xl" />
              <SiRedux className=" text-2xl" />
              <SiSass className=" text-2xl" />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
