import React from "react";
import Head from "next/head";
import Image from "next/image";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import {
  SiJavascript,
  SiMongodb,
  SiPhp,
  SiReact,
  SiTypescript,
  SiSass,
  SiNodedotjs,
  SiRedux,
} from "react-icons/si";
import { ImSpinner9 } from "react-icons/im";
import planet1 from "../public/planet.svg";
import planet2 from "../public/planet2.svg";
import planet3 from "../public/planet3.svg";
import planet4 from "../public/planet4.svg";
import { useState, useEffect, useRef } from "react";
import { delay, motion } from "framer-motion";
import AOS from "aos";
import "aos/dist/aos.css";

export default function Home() {
  const [darkMode, setDarkmode] = useState(false);
  useEffect(() => {
    AOS.init();
  }, []);

  const svgVariant = {
    hidden: { rotate: -180 },
    visible: {
      rotate: 0,
      transion: { duration: 5 },
    },
  };

  const [stickyClass, setstickyClass] = useState("relative");
  useEffect(() => {
    window.addEventListener("scroll", stickNavbar);
    return () => {
      window.removeEventListener("scroll", stickNavbar);
    };
  }, []);
  const stickNavbar = () => {
    if (window !== undefined) {
      let windowHeight = window.scrollY;
      windowHeight > 200
        ? setstickyClass(" fixed top-0  z-50 w-4/5")
        : setstickyClass("relative");
    }
  };

  const section1 = useRef();
  const section2 = useRef();
  const section3 = useRef();

  const scrollTo = (section) => {
      section.current.scrollIntoView({ behavior: 'smooth'})
    
  }
  

  return (
    <div className={`${darkMode ? "dark" : ""} container  `}>
     
      <Head>
        <title>BeardKoda </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" relative bg-[#fffafa] px-10 md:px-20 lg:px-40  dark:bg-gray-800">
        <section className=" absolute top-0 w-4/5 z-50 ">
          <nav
            className={`py-10 mb-12 flex justify-between items-center ${stickyClass}`}
          >
            <h1 className=" text-xl font-semibold font-burtons dark:text-white">
              BeardKoda
            </h1>
            <ul className=" flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkmode(!darkMode)}
                  className=" text-2xl cursor-pointer  dark:text-white"
                />
              </li>
              <li>
                <motion.div
                  whileHover={{ scale: 1.2 }}
                  whileTap={{ scale: 0.9 }}
                  transition={{ type: "spring", stiffness: 400, damping: 17 }}
                  className=" ml-5"
                >
                  <a
                    href="https://www.linkedin.com/in/joshua-akinsuyi/"
                    className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-7"
                  >
                    Contact Me
                  </a>
                </motion.div>
              </li>
            </ul>
          </nav>
        </section>
    
    
        <section  className=" relative flex justify-center flex-col items-center min-h-screen snap-center ">
          <div>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              xmlnsXlink="http://www.w3.org/1999/xlink"
              x="0"
              y="0"
              viewBox="0 0 1024 1024"
              className="svg sm:right-22"
            >
              <path
                id="followPath"
                d="M394.1-214.9c-49.7 89.4 114.4 192.8 175.5 475.1 13 60.1 85.4 424-98.1 552.6-95.7 67-267.2 74.5-346.3-22.1-70.8-86.5-49-233.9 19.2-305.2 102.4-107 353.9-89.1 593.2 96.5 139.6 107 294.1 258.4 415 468.6 19.2 33.5 36.6 66.6 52.3 99.3 13 8.6 34 19.5 53.3 13.2 148-48.6 165.1-1094.5-338.5-1374.8-196-109.1-470.7-102.1-525.6-3.2z"
              ></path>
              <path
                id="airbody"
                d="M394.1-214.9c-49.7 89.4 114.4 192.8 175.5 475.1 13 60.1 85.4 424-98.1 552.6-95.7 67-267.2 74.5-346.3-22.1-70.8-86.5-49-233.9 19.2-305.2 102.4-107 353.9-89.1 593.2 96.5 139.6 107 294.1 258.4 415 468.6 19.2 33.5 36.6 66.6 52.3 99.3 13 8.6 34 19.5 53.3 13.2 148-48.6 165.1-1094.5-338.5-1374.8-196-109.1-470.7-102.1-525.6-3.2z"
              ></path>
              <path id="airplain" d="M8.04 84L92 48 8.04 12 8 40l60 8-60 8z">
                <animateMotion
                  fill="freeze"
                  dur="15s"
                  repeatCount="indefinite"
                  rotate="auto"
                  href="#airplain"
                >
                  <mpath href="#followPath"></mpath>
                </animateMotion>
              </path>
            </svg>
          </div>
          <div className=" text-center p-10 pt-50 dark:text-white">
            <p>Hi!, It's </p>
            <h2
              className=" text-2xl text-teal-500 font-semibold pb-2 md:text-3xl lg:text-5xl"
              data-aos="fade-right"
              data-aos-duration="300"
            >
              BeardKoda{" "}
              <span className=" text-sm text-black dark:text-white">
                here 🤞,
              </span>
            </h2>
            <h3 className=" text-xl py-2 font-medium md:text-2xl lg:text-5xl " data-aos="fade-down" data-aos-duration="3000">
              I'm a Software Engineer,
            </h3>
            <p className=" text-md py-5 leading-7 text-gray-800 md:text-xl max-w-xl mx-auto lg:text-xl max-w-xl mx-auto dark:text-white" data-aos="zoom-in-up" data-aos-duration="3000">
              Automation is everything to me, I love learning new things
              everyday from programming languages, programming tools, automation
              tools and Games.
            </p>
          </div>
          <motion.div
            className=" absolute top-40 right-60 "
            initial={{ x: 0 }}
            animate={{
              rotate: [
                0, 30, 60, 90, 120, 150, 180, 210, 240, 270, 300, 330, 360,
              ],
            }}
            transition={{
              type: "spring",
              duration: 1,
              bounce: 0.1,
              repeat: Infinity,
            }}
            whileHover={{ scale: 1.1 }}
            whileTap={{ scale: 2.2 }}
          >
            <ImSpinner9 className=" text-4xl text-orange-600" />
          </motion.div>
          <div className=" text-5xl flex justify-center gap-5 py-1 text-gray-500 dark:text-teal-500">
            <motion.a
              href="https://www.linkedin.com/in/joshua-akinsuyi/"
              variants={svgVariant}
              initial="hidden"
              animate="visible"
              whileHover={{ scale: 1.2, rotate: [30] }}
              whileTap={{ scale: 0.9 }}
              transition={{ type: "spring", stiffness: 100, damping: 17 }}
            >
              <AiFillLinkedin />
            </motion.a>
            <motion.a
              href="https://twitter.com/BeardKoda"
              variants={svgVariant}
              initial="hidden"
              animate="visible"
              whileHover={{ scale: 1.2, rotate: [30] }}
              whileTap={{ scale: 0.9 }}
              transition={{ type: "spring", stiffness: 100, damping: 17 }}
            >
              <AiFillTwitterCircle />
            </motion.a>
            <motion.a
              href="https://github.com/BeardKoda"
              variants={svgVariant}
              initial="hidden"
              animate="visible"
              whileHover={{ scale: 1.2, rotate: [30] }}
              whileTap={{ scale: 0.9 }}
              transition={{ type: "spring", stiffness: 100, damping: 17 }}
            >
              <AiFillGithub />
            </motion.a>
          </div>
          <div>
            <Image
              src={planet1}
              className="  absolute opacity-40 top-80 right-10 h-10"
              alt="planet"
            />
            <Image
              src={planet2}
              className=" absolute opacity-40 top-80 left-40 h-10"
              alt="planet"
            />
            <Image
              src={planet4}
              className=" absolute opacity-40 top-80 right-60 h-10"
              alt="planet"
            />
            <Image
              src={planet3}
              className=" absolute opacity-40 bottom-90 -left-40 h-10"
              alt="planet"
            />
          </div>
        </section>

        <section className=" relative min-h-screen flex justify-center flex-col items-center snap-center ">
          <div>
            <div className="text-center my-10  ">
              <h3
                className={`text-3xl py-1 text-teal-500 justify-center flex`}
               
              >
                Services I offer
              </h3>
              <p
                className=" text-md  py-5 leading-8 text-gray-800 text-center md:text-xl max-w-xl mx-auto lg:text-xl max-w-xl mx-auto dark:text-white"
               
              >
                "since the beginning of my journey as a Developer, I've done
                remote work for <span className=" text-teal-500">agencies</span>
                , consulted for <span className=" text-teal-500">startups</span>{" "}
                and collaborated with talented people to create didgital product
                for both business and consumer use."
              </p>
          
              <p
                className=" text-md py-5 leading-7 text-center text-gray-800 md:text-xl max-w-xl mx-auto lg:text-xl max-w-xl mx-auto dark:text-white"
              
              >
                I offer from a wide range of Services, including Database
                Analyst, FullStack Devloper And DataScientist.
              </p>
            </div>
            <div id="light">
                <div id="lineh1"></div>
                <div id="lineh2"></div>
              </div>
          </div>
{/* 
          data-aos="fade-up"
                data-aos-duration="3000" */}
          
        </section>

        <section className=" relative min-h-screen flex justify-center flex-col items-center snap-center ">
          {/* <div data-aos="fade-up" data-aos-duration="3000"> */}
            <div className=" text-center  mt-10 py-14 ">
              <h4 className=" text-3xl py-1 text-teal-500 text-center mb-3">
                Skills
              </h4>
              <p className=" text-center md:text-xl max-w-2xl mx-auto lg:text-xl max-w-xl mx-auto dark:text-white">
                4 years+, a ton of tutorials and online courses, here I am. A
                passion of mine is translating logic and designs into code. Here
                are some the tools I use
              </p>
            </div>
          {/* </div> */}

          <div className="grid  grid-cols-4 text-center grid-rows-2  md:ma-w-xl lg: max-w-xl mx-auto   dark:text-teal-500">
            {/* <div data-aos="fade-up-left" data-aso-duration=" 3000">
              <SiJavascript className=" m-4  text-2xl" />
            </div>
            <div data-aos="fade-up-left" data-aso-duration=" 3000">
              <SiMongodb className=" m-4  text-2xl" />
            </div>
            <div data-aos="zoom-in" data-aso-duration=" 3000">
              <SiPhp className="  m-4  text-2xl" />
            </div>
            <div data-aos="fade-up-left" data-aso-duration=" 3000">
              <SiReact className="  m-4 text-2xl" />
            </div>
            <div data-aos="fade-up-left" data-aso-duration=" 3000">
              <SiTypescript className="  m-4  text-2xl" />
            </div>
            <div data-aos="fade-up-left" data-aso-duration=" 3000">
              <SiNodedotjs className="  m-4  text-2xl" />
            </div>
            <div data-aos="fade-up-left" data-aso-duration=" 3000">
              <SiRedux className="  m-4 text-2xl" />
            </div>
            <div data-aos="fade-right" data-aso-duration=" 3000">
              <SiSass className="  m-4  text-2xl" />
            </div> */}
            <SiJavascript className=" m-4  text-2xl" />
            <SiJavascript className=" m-4  text-2xl" />
            <SiJavascript className=" m-4  text-2xl" />
            <SiJavascript className=" m-4  text-2xl" />
            <SiJavascript className=" m-4  text-2xl" />
            <SiJavascript className=" m-4  text-2xl" />
            <SiJavascript className=" m-4  text-2xl" />
            <SiJavascript className=" m-4  text-2xl" />
            
          </div>
        </section>
            
      </main>
      
    </div>
  );
}

//   